### ISSUE TITLE
Fetched bad result from Twitter

### ISSUE THREAD

**Issue by danielearning** [meddelare/meddelare-node-counters#5] opened 2015-11-22 10:51 UTC
I use the Meddelare middleware in my nodejs server.
Recently I started receiving a `-1` as the Twitter count of shares, and getting these log lines in my server:

```
MeddelareCounters twitter 'https://......../' fetched bad result { cause: [Error: No well-formed body in response.], 
isOperational: true }
```

**Comment by joelpurra** [comment] 2015-11-22 11:34
@danielearning: I can confirm that the values returned from Twitter are not looking the way they used to.
https://cdn.api.twitter.com/1/urls/count.json?url=https://meddelare.com/

Looking into the issue, I was surprised to learn that Twitter has _shut down access to the share count url_. A workaround is to use their Search API, which still won't give an equivalent share counts (as it seems). Getting the full count would require using Twitter's Gnip, which is a _commercial enterprise service_.

From Twitter's blog post [Hard decisions for a sustainable platform](https://blog.twitter.com/2015/hard-decisions-for-a-sustainable-platform):

> Recently, we announced a new design for our Tweet and follow buttons, as well as a deprecation of the Tweet count feature. We expect to ship these changes by Nov. 20, 2015.

And now:

> Update Nov. 20, 2015: As described above, we have now shipped the updated Tweet Button and removed the Tweet count endpoint. We appreciate your feedback over the past 60 days on how you have used these counts, and look forward to incorporating it as we create and improve tools to integrate Twitter content into your apps and websites.

Re-enabling some kind of Twitter share count (still not a very complete one) in Meddelare would require an OAuth-enabled Twitter API package to replace the current call. It would additionally require Meddelare server-operators to [register their own Twitter App](https://apps.twitter.com/) and provide OAuth tokens as configuration values. Patches are always welcome! Any takers?

Because the share count still won't be what it used to be, we could follow Twitter's lead and consider dropping Twitter support altogether. It would be a shame, but it's also a quite realistic move. What do you think?

**Comment by joelpurra** [comment] 2015-11-23 07:42
Here's one solution: removing the count and replacing it with a twitter logotype.
https://github.com/copyblogger/genesis-simple-share/issues/58#issuecomment-145157553

**Comment by brugeman** [comment] 2016-01-24 10:59
Hi! There is a free third-party alternative to the shut down API: newsharecounts.com. Maybe it could suit your needs.

**Comment by joelpurra** [comment] 2020-12-07 14:31
Closing due to Meddelare project shutdown (https://github.com/meddelare/meddelare-superproject/issues/8).

**Closed as completed by joelpurra** 2020-12-07 14:31 UTC
